### ISSUE TITLE
Integrate fuzzy path matching for games launch

### ISSUE THREAD

**Issue by wizzomafizzo** [ZaparooProject/zaparoo-core#23]
In the same way that launchsync does, all partial path matches and regex

This requires an index to be created of games, which cannot be done on the fly before a launch (it takes too long) like launchsync does. Need some thought about when is ideal to create an index and recreate the cached index.

**Comment by asturur** [comment]
What is the features that changes here? can you describe what this enhancement achieve?

**Comment by wizzomafizzo** [comment]
This app lets you create a list of games which is converted to mgl shortcut files in the mister menu: https://github.com/wizzomafizzo/mrext/blob/main/docs/launchsync.md#game-sections

I wanted these games lists to be portable, which meant it wouldn't work if you put an absolute path for each game. So I came up with a format that you can put a filename partial match or regexp as an option to match the game's path, that way the game can be in any path or have any rom tags in the filename and there's still a high chance of picking it up across different misters

The method is not perfect but it would go a long way to making cards portable between systems (like if you wanted to sell them preloaded) or after a user has rearranged their files. Maybe it could even be extended and combined with other commands, like how about a card that launched a random "mario" game
