### ISSUE TITLE
Connection string being set to "null"

### ISSUE THREAD

**Issue by wizzomafizzo** [ZaparooProject/zaparoo-core#64]
Have had 2 reports on Discord so far where their tapto.ini file's `connection_string` setting was set to the string `null`. I'm guessing an empty value on the API is being converted to null when modifying settings? It doesn't seem to be widespread.

**Comment by asturur** [comment]
should it be empty string in case? or no entry at all?

**Comment by wizzomafizzo** [comment]
either is fine. they will both result in an empty string in Go
