### ISSUE TITLE
tapto app can't choose NeoGeo

### ISSUE THREAD

**Issue by xenyou** [ZaparooProject/zaparoo-core#94]
tapto app can't choose NeoGeo in 'Search for Game'.
There is only NeoGeo CD.

![IMG_0264](https://github.com/user-attachments/assets/5d743316-18f4-4a5a-bb86-b44f2b07386c)

I'm using iOS version.

https://apps.apple.com/us/app/tapto-life/id6480331015

**Comment by wizzomafizzo** [comment]
Thanks for your report. I think I've identified why this happens now. I'll make sure it's fixed in the next app update :)
