### ISSUE TITLE
Launching cores causes UART reader to disconnect

### ISSUE THREAD

**Issue by wizzomafizzo** [ZaparooProject/zaparoo-core#99]
- On MiSTer. Can replicate (so far) with NES and PSX core.
- Can replicate by just using `load_core .../NES.rbf > /dev/MiSTer_cmd`
- Reader immediately reconnects for me, does not for other report, required service restart
- Only began happening after a recent MiSTer update, same TapTo version

**Comment by NolanNicholson** [comment]
It turns out the service restart in the NES core is only required if, in the NES core settings, "System" -> "UART mode" is set to "MIDI", with MidiLink also set to "USB." The initial MIDI handshake then crashes the UART reader.

**Comment by wizzomafizzo** [comment]
It was a conflict with tty2oled! Will be fixed in one of the other "display support" issues
